# Configuração específica para o frontend no Render
# Este arquivo pode ser usado se você quiser configurar o frontend separadamente

services:
  - type: web
    name: soscancer-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /index.html
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    envVars:
      - key: VITE_API_URL
        value: https://soscancer-backend.onrender.com
