[tool.ruff]
target-version = "py312"
line-length = 100
extend-select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
  "B",  # flake8-bugbear
]
exclude = [
  ".venv",
  "data",
  "__pycache__",
]

[tool.ruff.lint.isort]
known-first-party = ["app"]
combine-as-imports = true


